language: objective-c

global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=MyFramework/MyFramework.xcworkspace
    - IOS_SCHEME="MyFrameworkiOS"
    - IOS_SDK=iphonesimulator11.4
    - OSX_SCHEME="MyFrameworkOSX"
    - OSX_SDK=macosx10.13
    - TVOS_SCHEME="MyFrameworkTVOS"
    - TVOS_SDK=appletvsimulator11.4

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
