set -e
language: swift
os: osx
osx_image: xcode9.4
env:

global:
 - LC_CTYPE=en_US.UTF-8
 - LANG=en_US.UTF-8
 - WORKSPACE=MyFramework/MyFramework.xcworkspace
 - IOS_SCHEME="MyFrameworkiOS"
 - IOS_SDK=iphonesimulator11.4
 - OSX_SCHEME="MyFrameworkOSX"
 - OSX_SDK=macosx10.13
 - TVOS_SCHEME="MyFrameworkTVOS"
 - TVOS_SDK=appletvsimulator11.4

script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
- if [ $RUN_TESTS == "YES" ]; then
 xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
else
 xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
fi

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
 pod lib lint --private --verbose;
fi
